# Generated by Django 4.2.6 on 2025-02-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_settingsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='cstimer_animation_duration',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='cstimer_inspection_voice_alert',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
