# Generated by Django 4.2.6 on 2025-04-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_settingsmodel_cstimer_animation_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='cstimer_camera_position_phi',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='cstimer_camera_position_theta',
            field=models.IntegerField(default=0),
        ),
    ]
