# Generated by Django 4.2.6 on 2024-04-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scramblemodel',
            old_name='scramble',
            new_name='moves',
        ),
    ]
