# Generated by Django 4.2.6 on 2023-10-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvemodel',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='solvemodel',
            name='contest_submitted',
        ),
    ]
