# Generated by Django 4.2.6 on 2023-10-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundmodel',
            name='avg_ms',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
