# Generated by Django 4.2.6 on 2023-10-19 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scramblemodel',
            name='contest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contests.contestmodel'),
            preserve_default=False,
        ),
    ]
