# Generated by Django 4.2.6 on 2024-11-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundsessionmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='solvemodel',
            options={'ordering': ['id']},
        ),
    ]
