# Generated by Django 4.2.6 on 2023-10-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_alter_roundmodel_avg_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundmodel',
            name='avg_ms',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
