# Generated by Django 4.2.6 on 2023-10-19 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_scramblemodel_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvemodel',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_set', to='contests.contestmodel'),
        ),
    ]
