# Generated by Django 4.2.6 on 2023-10-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_remove_solvemodel_contest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scramblemodel',
            name='position',
            field=models.CharField(max_length=10),
        ),
    ]
