# Generated by Django 4.2.6 on 2024-05-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_rename_scramble_scramblemodel_moves'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleBestSolveLeaderboardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.solvemodel')),
            ],
        ),
    ]
