# Generated by Django 4.2.6 on 2024-05-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_singlebestsolveleaderboardmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SingleBestSolveLeaderboardModel',
            new_name='SingleResultLeaderboardModel',
        ),
    ]
