# Generated by Django 4.2.6 on 2023-10-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_solvemodel_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='scramblemodel',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
