# Generated by Django 4.2.6 on 2023-10-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_scramblemodel_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scramblemodel',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
