# Generated by Django 4.2.6 on 2023-10-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_rename_roundmodel_roundsessionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solvemodel',
            old_name='round',
            new_name='round_session',
        ),
    ]
