# Generated by Django 4.2.6 on 2024-05-27 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0004_rename_singlebestsolveleaderboardmodel_singleresultleaderboardmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleresultleaderboardmodel',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
