# Generated by Django 4.2.6 on 2024-05-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_singleresultleaderboardmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleresultleaderboardmodel',
            name='user',
        ),
    ]
