# Generated by Django 4.2.6 on 2023-10-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_scramblemodel_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='scramblemodel',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contests.disciplinemodel'),
            preserve_default=False,
        ),
    ]
