# Generated by Django 4.2.6 on 2023-10-28 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0005_rename_round_solvemodel_round_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundsessionmodel',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_session_set', to='contests.contestmodel'),
        ),
        migrations.AlterField(
            model_name='roundsessionmodel',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_session_set', to='contests.disciplinemodel'),
        ),
        migrations.AlterField(
            model_name='roundsessionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_session_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
