# Generated by Django 4.2.6 on 2023-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_alter_roundsessionmodel_contest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundsessionmodel',
            name='dnf',
            field=models.BooleanField(default=False),
        ),
    ]
