# Generated by Django 4.2.6 on 2024-06-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_remove_singleresultleaderboardmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleresultleaderboardmodel',
            name='time_ms',
            field=models.IntegerField(db_index=True, default=None),
            preserve_default=False,
        ),
    ]
