# Generated by Django 4.2.6 on 2023-10-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_alter_solvemodel_scramble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scramblemodel',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scramble_set', to='contests.contestmodel'),
        ),
        migrations.AlterField(
            model_name='solvemodel',
            name='scramble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.scramblemodel'),
        ),
    ]
