# Generated by Django 4.2.6 on 2023-10-31 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_alter_solvemodel_time_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvemodel',
            name='contest',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='solve_set', to='contests.contestmodel'),
            preserve_default=False,
        ),
    ]
