# Generated by Django 4.2.6 on 2023-10-22 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0008_alter_scramblemodel_contest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scramblemodel',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scramble_set', to='contests.disciplinemodel'),
        ),
        migrations.AlterField(
            model_name='solvemodel',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_set', to='contests.disciplinemodel'),
        ),
        migrations.AlterField(
            model_name='solvemodel',
            name='scramble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_set', to='contests.scramblemodel'),
        ),
        migrations.AlterField(
            model_name='solvemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
