# Generated by Django 4.2.6 on 2023-10-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_alter_scramblemodel_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestmodel',
            name='name',
            field=models.IntegerField(unique=True),
        ),
    ]
