# Generated by Django 4.2.6 on 2024-08-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_tnoodlescrambles_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TnoodleScrambles',
            new_name='TnoodleScramblesModel',
        ),
    ]
