# Generated by Django 4.2.6 on 2023-11-01 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_alter_solvemodel_reconstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
