# Generated by Django 4.2.6 on 2024-08-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_rename_tnoodlescrambles_tnoodlescramblesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnoodlescramblesmodel',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
