# Generated by Django 4.2.6 on 2023-10-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_contestmodel_ongoing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestmodel',
            old_name='name',
            new_name='contest_id',
        ),
    ]
