# Generated by Django 4.2.6 on 2023-10-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_rename_name_contestmodel_contest_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestmodel',
            old_name='contest_id',
            new_name='contest_number',
        ),
    ]
