# Generated by Django 4.2.6 on 2023-10-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_rename_contest_id_contestmodel_contest_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvemodel',
            name='changed_to_extra',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
