# Generated by Django 4.2.6 on 2023-10-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_solvemodel_contest_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvemodel',
            name='contest_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
