# Generated by Django 4.2.6 on 2023-10-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0017_alter_solvemodel_contest_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvemodel',
            name='changed_to_extra',
        ),
        migrations.AddField(
            model_name='solvemodel',
            name='extra_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
