# Generated by Django 4.2.6 on 2023-10-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_remove_solvemodel_changed_to_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvemodel',
            name='dnf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solvemodel',
            name='state',
            field=models.CharField(default='pending', max_length=96),
        ),
    ]
