# Generated by Django 4.2.6 on 2023-10-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0019_alter_solvemodel_dnf_alter_solvemodel_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scramblemodel',
            name='num',
        ),
    ]
