# Generated by Django 4.2.6 on 2023-10-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0020_remove_scramblemodel_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='scramblemodel',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
