# Generated by Django 4.2.6 on 2023-10-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0021_scramblemodel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvemodel',
            name='reconstruction',
            field=models.TextField(max_length=15048),
        ),
    ]
